# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Azure Pipeline Template for updating training dataset
# The dataset in this example is updated for illustration purposes only, the data downloaded is the same


parameters:
- name: sdkVersion
  type: string
- name: serviceConnection
  type: string
- name: resourceGroup
  type: string
- name: amlWorkspaceName
  type: string
- name: amlTrainDatasetName
  type: string
- name: amlTestDatasetName
  type: string
- name: containerName
  type: string
- name: accountName
  type: string
- name: accountKey
  type: string
- name: trainDataPathPrefix
  type: string
- name: testDataPathPrefix
  type: string



jobs:

- job: download_new_data
  displayName: 'Download New Sample Files'
  steps:

    - task: UsePythonVersion@0
      displayName: 'Use Python 3.7'
      inputs:
        versionSpec: 3.7
    
    - task: AzureCLI@1
      displayName: 'Download Sample Files and Upload to AML datastore'
      inputs:
        azureSubscription: ${{parameters.serviceConnection}}
        scriptLocation: inlineScript
        inlineScript: |
          # Install dependencies
          python -m pip install --upgrade pip && python -m pip install azureml-sdk==${{parameters.sdkVersion}}
          python Automated_ML/mlops-pipelines/scripts/download_data.py \
                        --resource-group ${{parameters.resourceGroup}} \
                        --workspace-name ${{parameters.amlWorkspaceName}} \
                        --container-name ${{parameters.containerName}} \
                        --account-name ${{parameters.accountName}} \
                        --account-key ${{parameters.accountKey}} \
                        --train-data-path-prefix ${{parameters.trainDataPathPrefix}} \
                        --test-data-path-prefix ${{parameters.testDataPathPrefix}} \
                        --train-target-path ${{parameters.trainDataPathPrefix}} \
                        --test-target-path ${{parameters.testDataPathPrefix}} \
                        --subscription-id $(az account show --query id -o tsv)
          register_dataset_script=Automated_ML/mlops-pipelines/scripts/register_or_update_dataset.py
          # Register dataset
          python $register_dataset_script --path ${{parameters.trainDataPathPrefix}} \
                                          --name ${{parameters.amlTrainDatasetName}} \
                                          --subscription-id $(az account show --query id -o tsv) \
                                          --resource-group ${{parameters.resourceGroup}} \
                                          --workspace-name ${{parameters.amlWorkspaceName}}
          python $register_dataset_script --path ${{parameters.testDataPathPrefix}} \
                                          --name ${{parameters.amlTestDatasetName}} \
                                          --subscription-id $(az account show --query id -o tsv) \
                                          --resource-group ${{parameters.resourceGroup}} \
                                          --workspace-name ${{parameters.amlWorkspaceName}}
      name: download_files