# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Pipeline that runs AML Pipeline for model training

# trigger:
#   branches:
#     include:
#     - v2-preview
#   paths:
#     include:
#     - Custom_Script/mlops-pipelines/3-modeling/*
#     - Custom_Script/mlops-pipelines/scripts/deploy_grouped_models.py
#     - Custom_Script/scripts/forecast_webservice.py
#     - Custom_Script/scripts/routing_webservice.py
#     - Custom_Script/scripts/routing_webservice.conda.yml

# schedules:
# - cron: "0 0 * * *"
#   displayName: 'Daily training at midnight'
#   branches:
#     include:
#     - v2-preview
#   always: true

variables:
- template: ../many-models-variables.yml
- group: manymodels-vg

pool:
  vmImage: ubuntu-latest

stages:

# There is no data to update in this example, but in the general case 
# the registered dataset should be updated before retraining.
# - stage: update_data
#   displayName: 'Update Data for Training'
#   jobs:
#   - template: update-data/update-data.template.yml

- stage: run_training
  displayName: 'Run Model Training'
  jobs:
  - template: run-training/run-training.template.yml
    parameters:
      serviceConnection: '$(SERVICECONNECTION_WORKSPACE)'
      resourceGroup: '$(RESOURCE_GROUP)'
      amlWorkspaceName: '$(AMLWORKSPACE_NAME)'
      trainingPipelineName: '$(AML_TRAINING_PIPELINE_NAME)'

- stage: deploy_models_aci
  displayName: 'Deploy Models to ACI'
  dependsOn: run_training
  condition: eq(variables['DEPLOY_ACI'], 'true')
  jobs:
  - template: deploy-models/deploy-models.template.yml
    parameters:
      sdkVersion: '$(SDK_VERSION)'
      serviceConnection: '$(SERVICECONNECTION_WORKSPACE)'
      resourceGroup: '$(RESOURCE_GROUP)'
      amlWorkspaceName: '$(AMLWORKSPACE_NAME)'
      deploymentType: aci
      amlAksName: ''
      groupingTags: '$(AML_MODEL_GROUPING_TAGS)'
      routingModelName: '$(AML_ROUTING_MODEL_NAME)'
      routingModelTagName: '$(AML_ROUTING_MODEL_TAG_NAME)'
      routingModelTagValue: '$(AML_ROUTING_MODEL_TAG_VALUE)'
      routingServiceName: '$(AML_ROUTING_WEBSERVICE)'

- stage: deploy_models_aks
  displayName: 'Deploy Models to AKS'
  dependsOn: run_training
  condition: and(eq(variables['DEPLOY_AKS'], 'true'), variables['AML_AKS_NAME'])
  jobs:
  - template: deploy-models/deploy-models.template.yml
    parameters:
      sdkVersion: '$(SDK_VERSION)'
      serviceConnection: '$(SERVICECONNECTION_WORKSPACE)'
      resourceGroup: '$(RESOURCE_GROUP)'
      amlWorkspaceName: '$(AMLWORKSPACE_NAME)'
      deploymentType: aks
      amlAksName: '$(AML_AKS_NAME)'
      groupingTags: '$(AML_MODEL_GROUPING_TAGS)'
      routingModelName: '$(AML_ROUTING_MODEL_NAME)'
      routingModelTagName: '$(AML_ROUTING_MODEL_TAG_NAME)'
      routingModelTagValue: '$(AML_ROUTING_MODEL_TAG_VALUE)'
      routingServiceName: '$(AML_ROUTING_WEBSERVICE)'
